name: Build Docker Image from External Repo

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-push:
    name: Buid and push Docker image to GitHub Container registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Get tdlib ref
        uses: octokit/request-action@v2.x
        id: get-tdlib-ref
        with:
          route: GET /repos/tdlib/td/branches/master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Cache tdlib
        id: cache-tdlib
        uses: actions/cache@v4
        with:
          path: tdlib
          key: tdlib-${{fromJson(steps.get-tdlib-ref.outputs.data).commit.sha}}

      - name: Checkout tdlib
        if: steps.cache-tdlib.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          ref: ${{fromJson(steps.get-tdlib-ref.outputs.data).commit.sha}}
          repository: tdlib/td
          token: ${{secrets.GITHUB_TOKEN}}
          path: tdlib

      - name: Login to GitHub Container registry
        if: steps.cache-tdlib.outputs.cache-hit != 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set env vars
        if: steps.cache-tdlib.outputs.cache-hit != 'true'
        run: |
          LATEST_COMMIT=${{fromJson(steps.get-tdlib-ref.outputs.data).commit.sha}}
          LATEST_COMMIT_SHORT=${LATEST_COMMIT:0:7}
          echo "LATEST_COMMIT=$LATEST_COMMIT" >> $GITHUB_ENV
          echo "LATEST_COMMIT_SHORT=$LATEST_COMMIT_SHORT" >> $GITHUB_ENV

      - name: Build Docker image
        if: steps.cache-tdlib.outputs.cache-hit != 'true'
        run: |
          tag=ghcr.io/${{ github.repository }}:${{ env.LATEST_COMMIT_SHORT }}-alpine
          docker build --network host --build-arg TD_COMMIT=${{ env.LATEST_COMMIT }} --tag $tag .
          docker push $tag
